language: java

jdk:
    - openjdk8

before_install:
    - chmod -R +x src
    - chmod +x gradlew

script:
    - ./gradlew clean build check jacocoTestReport coveralls

cache:
    bundler: true
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
