language: java

jdk:
    - oraclejdk8
    - openjdk8

env:
    - CODECOV_TOKEN="e598bb94-cd7c-4d66-86a1-223f9989b460"

before_install:
    - chmod +x gradlew
    - chmod +x gradle/wrapper/gradle-wrapper.jar

script:
    - ./gradlew check build
    - ./gradlew coveralls

after_success:
    - bash <(curl -s https://codecov.io/bash)

cache:
    bundler: true
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
