language: java

jdk:
    - oraclejdk8
    - openjdk8

before_install:
    - chmod +x gradlew

after_success:
    - bash <(curl -s https://codecov.io/bash)


cache:
    bundler: true
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
