language: java

jdk:
    - oraclejdk8
    - openjdk8

before_install:
    - chmod -R +x src
    - chmod +x gradlew

script:
    - ./gradlew clean build check jacocoTestReport coveralls

after_success:
    - bash <(curl -s https://codecov.io/bash)

cache:
    bundler: true
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
