name: Release to Maven Central
on:
  release:
    types: [ published ]

jobs:
  deploy:
    name: Publish artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Decrypt private key
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.SIGNING_PASSWORD}}" --output secring.txt pub_key.gpg
      - name: Make gradle executable
        run: chmod +x gradlew
      - name: Publish to Maven Central
        id: gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          SONATYPE_USERNAME: mpgirro
          SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
          SIGNING_PASSWORD: ${{secrets.SIGNING_PASSWORD}}
